### ISSUE TITLE
Kibana Installation with ElasticSearch 1.4 Fails Silently

### ISSUE THREAD

**Issue by anEffingChamp** [packetbeat/packetbeat#85] opened 2015-01-15 14:28 UTC
Installing your custom Kibana dashboard over ElasticSearch 1.4 fails silently with no description of the issue. Using the standard Kibana from ElasticSearch produces a more useful message that ElasticSearch settings are at fault.

**Comment by tsg** [comment] 2015-01-15 14:38
Hmm, in my tests Kibana3-packetbeat works with ES 1.4. In which way it didn't work? Also, which version from Kibana-ES did you try? Perhaps Kibana4?

**Comment by anEffingChamp** [comment] 2015-01-15 15:03
Standard Kibana3 fails with:
```
Connection Failed
Possibility #1: Your elasticsearch server is down or unreachable

This can be caused by a network outage, or a failure of the Elasticsearch process. If you have recently run a query that required a terms facet to be executed it is possible the process has run out of memory and stopped. Be sure to check your Elasticsearch logs for any sign of memory pressure.
Possibility #2: You are running Elasticsearch 1.4 or higher

Elasticsearch 1.4 ships with a security setting that prevents Kibana from connecting. You will need to set the following in your elasticsearch.yml:
http.cors.enabled: true
http.cors.allow-origin to the correct protocol, hostname, and port (if not 80) that your access Kibana from. Note that if you are running Kibana in a sub-url, you should exclude the sub-url path and only include the protocol, hostname and port. For example, http://mycompany.com:8080, not http://mycompany.com:8080/kibana.
Click back, or the home button, when you have resolved the connection issue.
```

Packetbeat Kibana3 simply reports:
```
Error Could not contact Elasticsearch at http://DNS:9200. Please ensure that Elasticsearch is reachable from your system.
```

Both versions are Kibana3.

**Comment by tsg** [comment] 2015-01-15 15:50
Ah, thanks, I can reproduce it now. The reason was that I was using [Packetbeat Deploy](http://packetbeat.com/deploy) which avoids CORS issues by using Nginx in front of ES. We'll sync the fork with the upstream Kibana.

**Comment by tsg** [comment] 2015-01-15 17:27
Fixed now by commits into the Kibana repo and the release there.

**Closed by tsg** 2015-01-15 17:27 UTC
Labels: bug
