### ISSUE TITLE
need help to debug why Packetbeat not capturing postgresql

### ISSUE THREAD

**Issue by harshamadala** [packetbeat/packetbeat#123] opened 2015-04-27 18:55 UTC
Can anyone help me how to debug why packetbeat not capturing postgresql packets. 

I tried running packetbeat -e -d "pgsql" and it keep on giving below logs
"pgsql.go:472: WARN Postgresql Message too short (length=1). Wait for more.
pgsql.go:630: DBG  Message not complete, but sending to the next layer
pgsql.go:723: WARN Response from unknown transaction. Ignoring."

Somewhere before I read that this is because of preparedstatements, but even commands which I ran in psql are not begin captured by packetbeat. Is there any way to debug what is the issue?

Thanks

**Comment by harshamadala** [comment] 2015-04-27 18:57
Configuration using:
device = "any"
[protocols.pgsql]
  ports = [5432]
[procs.monitored.pgsql]
  cmdline_grep = "postgres"

**Comment by tsg** [comment] 2015-04-27 19:05
You might have encryption on? See https://github.com/packetbeat/packetbeat/issues/90

**Comment by tsg** [comment] 2015-04-27 19:06
Sorry, this is the ticket I wanted to link to: https://github.com/packetbeat/packetbeat/issues/46

**Comment by harshamadala** [comment] 2015-04-28 09:02
Thanks for quick response.

We have encryption off. And I am getting 
"pgsql.go:723: WARN Response from unknown transaction. Ignoring." continuously. 
Is this because of prepared statements? How to debug this?

**Comment by tsg** [comment] 2015-04-28 09:05
Best would be to create a small trace, like this one:

    tcpdump -i any -s0 -w"trace.pcap" "port 5432"

And send it to us at info@packetbeat.com. We can than figure it out if it's because of prepared statements or something else.

**Comment by tsg** [comment] 2015-04-28 10:56
Thanks for the trace, indeed, it's using "unnamed prepared statements". You can see them showing up in wireshark as "T/D/C/Z".

Closing this one as a duplicate of #78. We'll try to figure out a solution.

**Closed by tsg** 2015-04-28 10:56 UTC
